### ISSUE TITLE
Replace AccuWeather with the National Weather Service, if possible

### ISSUE THREAD

**Issue by Banjoei** [WiiLink24/ForecastChannel#12]
AccuWeather has a history of releasing inaccurate forecasts that are 90-days long since weather forecasts past 8 to 10 days are essentially useless due to the amount of factors to account for that even the best computers cannot get right. The data from before that point though is sourced straight from the National Weather Service, which is a more reliable source of information. I'm not sure how this project works and cannot guarantee it'll be possible to do so, but the Weather Service offers an API of their own, with documentation located at [this link](https://www.weather.gov/documentation/services-web-api), and it would be wonderful to have the data for WiiLink24 be sourced from this more credible source.

**Comment by vabold** [comment]
Weird - I just looked up London on this service, but it only shows up as towns in the USA, which seems less accurate.

**Comment by Riddim-GLiTCH** [comment]
> AccuWeather has a history of releasing inaccurate forecasts[...]

This is not even true in most cases. Here in the Netherlands for instance it has been generally on point.

**Comment by JessTwolve** [comment]
AccuWeather has been known to be correct most of the time, and some errors are expected given the nature of forecasts. The existence of 90 day forecasts also doesn't subtract from the fact that the Weather Channel only uses 5 days in most regions and 7 in Japan. Not to mention that WiiLink is a global service, and using the U.S. National Weather Service would actively detract from many users' experience outside of the states.

**Comment by Banjoei** [comment]
I was concerned about nothing I guess, I _had_ recently heard some very negative comments about AccuWeather but in the end it doesn't really matter for this.
